In [20]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [2]:

def read_df_from_csv(path: str) -> pd.DataFrame:
    return pd.read_csv(
        filepath_or_buffer=path,
        sep=',',
        header=0,
        dtype={
        'ORIGIN_AIRPORT': str,
        'DESTINATION_AIRPORT': str,
        'SCHEDULED_DEPARTURE': str,
        'DEPARTURE_TIME': str,
        'SCHEDULED_ARRIVAL': str,
        'ARRIVAL_TIME': str
    },
    low_memory=True
    )

In [3]:
airlines_df = read_df_from_csv(path='data/airlines.csv')
airlines_df.describe()

       IATA_CODE                AIRLINE
count         14                     14
unique        14                     14
top           UA  United Air Lines Inc.
freq           1                      1

In [4]:
airports_df = read_df_from_csv(path='data/airports.csv')
airlines_df.describe()

       IATA_CODE                AIRLINE
count         14                     14
unique        14                     14
top           UA  United Air Lines Inc.
freq           1                      1

In [5]:
cancellation_df = read_df_from_csv(path='data/cancellation_codes.csv')
cancellation_df.describe()

       CANCELLATION_REASON CANCELLATION_DESCRIPTION
count                    4                        4
unique                   4                        4
top                      A          Airline/Carrier
freq                     1                        1

In [6]:
flights_df = read_df_from_csv(path='data/flights.csv')
print(flights_df.isna().sum())
flights_df.describe()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER              14721
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           86153
DEPARTURE_DELAY          86153
TAXI_OUT                 89047
WHEELS_OFF               89047
SCHEDULED_TIME               6
ELAPSED_TIME            105071
AIR_TIME                105071
DISTANCE                     0
WHEELS_ON                92513
TAXI_IN                  92513
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             92513
ARRIVAL_DELAY           105071
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4755640
SECURITY_DELAY         4755640
AIRLINE_DELAY          4755640
LATE_AIRCRAFT_DELAY    4755640
WEATHER_DELAY          4755640
dtype: int64

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,SCHEDULED_TIME,ELAPSED_TIME,...,WHEELS_ON,TAXI_IN,ARRIVAL_DELAY,DIVERTED,CANCELLED,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
count,5819079.0,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.732926e+06,5.730032e+06,5.730032e+06,5.819073e+06,5.714008e+06,...,5.726566e+06,5.726566e+06,5.714008e+06,5.819079e+06,5.819079e+06,1.063439e+06,1.063439e+06,1.063439e+06,1.063439e+06,1.063439e+06
mean,2015.0,6.524085e+00,1.570459e+01,3.926941e+00,2.173093e+03,9.370158e+00,1.607166e+01,1.357171e+03,1.416859e+02,1.370062e+02,...,1.471469e+03,7.434971e+00,4.407057e+00,2.609863e-03,1.544643e-02,1.348057e+01,7.615387e-02,1.896955e+01,2.347284e+01,2.915290e+00
std,0.0,3.405137e+00,8.783425e+00,1.988845e+00,1.757064e+03,3.708094e+01,8.895574e+00,4.980094e+02,7.521058e+01,7.421107e+01,...,5.221879e+02,5.638548e+00,3.927130e+01,5.102012e-02,1.233201e-01,2.800368e+01,2.143460e+00,4.816164e+01,4.319702e+01,2.043334e+01
min,2015.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-8.200000e+01,1.000000e+00,1.000000e+00,1.800000e+01,1.400000e+01,...,1.000000e+00,1.000000e+00,-8.700000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2015.0,4.000000e+00,8.000000e+00,2.000000e+00,7.300000e+02,-5.000000e+00,1.100000e+01,9.350000e+02,8.500000e+01,8.200000e+01,...,1.054000e+03,4.000000e+00,-1.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2015.0,7.000000e+00,1.600000e+01,4.000000e+00,1.690000e+03,-2.000000e+00,1.400000e+01,1.343000e+03,1.230000e+02,1.180000e+02,...,1.509000e+03,6.000000e+00,-5.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,3.000000e+00,0.000000e+00
75%,2015.0,9.000000e+00,2.300000e+01,6.000000e+00,3.230000e+03,7.000000e+00,1.900000e+01,1.754000e+03,1.730000e+02,1.680000e+02,...,1.911000e+03,9.000000e+00,8.000000e+00,0.000000e+00,0.000000e+00,1.800000e+01,0.000000e+00,1.900000e+01,2.900000e+01,0.000000e+00
max,2015.0,1.200000e+01,3.100000e+01,7.000000e+00,9.855000e+03,1.988000e+03,2.250000e+02,2.400000e+03,7.180000e+02,7.660000e+02,...,2.400000e+03,2.480000e+02,1.971000e+03,1.000000e+00,1.000000e+00,1.134000e+03,5.730000e+02,1.971000e+03,1.331000e+03,1.211000e+03

In [7]:
def fix_hhmm(hhmm_series, year, month, day):
    hhmm_series = hhmm_series.fillna(0).astype(int)

    overflow = hhmm_series == 2400
    hhmm_series[overflow] = 0

    hh = hhmm_series // 100
    mm = hhmm_series % 100

    dt = pd.to_datetime(dict(year=year, month=month, day=day)) + pd.to_timedelta(hh, unit='h') + pd.to_timedelta(mm, unit='m')

    dt[overflow] += pd.Timedelta(days=1)

    return dt

flights_df['SCHEDULED_DEPARTURE_dt'] = fix_hhmm(
    flights_df['SCHEDULED_DEPARTURE'],
    flights_df['YEAR'].astype(int),
    flights_df['MONTH'].astype(int),
    flights_df['DAY'].astype(int)
)

In [22]:

time_cols = ['SCHEDULED_DEPARTURE','DEPARTURE_TIME','SCHEDULED_ARRIVAL','ARRIVAL_TIME', 'WHEELS_OFF', 'WHEELS_ON']

for col in time_cols:
    valid_mask = flights_df[col].notna()

    hhmm = flights_df.loc[valid_mask, col].astype(int).astype(str).str.zfill(4)
    hours = hhmm.str[:2].astype(int)
    minutes = hhmm.str[2:].astype(int)

    flights_df.loc[valid_mask, col + '_dt'] = (
        pd.to_datetime(
            pd.DataFrame({
                'year': flights_df.loc[valid_mask, 'YEAR'],
                'month': flights_df.loc[valid_mask, 'MONTH'],
                'day': flights_df.loc[valid_mask, 'DAY']
            })
        ) + pd.to_timedelta(hours, unit='h') + pd.to_timedelta(minutes, unit='m')
    )

for col in ['SCHEDULED_DEPARTURE_dt', 'DEPARTURE_TIME_dt', 'SCHEDULED_ARRIVAL_dt', 'ARRIVAL_TIME_dt', 'WHEELS_OFF_dt', 'WHEELS_ON_dt']:
    flights_df[col + '_min'] = flights_df[col].dt.hour * 60 + flights_df[col].dt.minute

flights_df.drop(columns=time_cols)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_DELAY,...,SCHEDULED_ARRIVAL_dt,ARRIVAL_TIME_dt,WHEELS_OFF_dt,WHEELS_ON_dt,SCHEDULED_DEPARTURE_dt_min,DEPARTURE_TIME_dt_min,SCHEDULED_ARRIVAL_dt_min,ARRIVAL_TIME_dt_min,WHEELS_OFF_dt_min,WHEELS_ON_dt_min
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,-11.0,...,2015-01-01 04:30:00,2015-01-01 04:08:00,2015-01-01 00:15:00,2015-01-01 04:04:00,5,1434.0,270,248.0,15.0,244.0
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,-8.0,...,2015-01-01 07:50:00,2015-01-01 07:41:00,2015-01-01 00:14:00,2015-01-01 07:37:00,10,2.0,470,461.0,14.0,457.0
2,2015,1,1,4,US,840,N171US,SFO,CLT,-2.0,...,2015-01-01 08:06:00,2015-01-01 08:11:00,2015-01-01 00:34:00,2015-01-01 08:00:00,20,18.0,486,491.0,34.0,480.0
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,-5.0,...,2015-01-01 08:05:00,2015-01-01 07:56:00,2015-01-01 00:30:00,2015-01-01 07:48:00,20,15.0,485,476.0,30.0,468.0
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,-1.0,...,2015-01-01 03:20:00,2015-01-01 02:59:00,2015-01-01 00:35:00,2015-01-01 02:54:00,25,24.0,200,179.0,35.0,174.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5819074,2015,12,31,4,B6,688,N657JB,LAX,BOS,-4.0,...,2015-12-31 08:19:00,2015-12-31 07:53:00,2015-12-31 00:17:00,2015-12-31 07:49:00,1439,1435.0,499,473.0,17.0,469.0
5819075,2015,12,31,4,B6,745,N828JB,JFK,PSE,-4.0,...,2015-12-31 04:46:00,2015-12-31 04:30:00,2015-12-31 00:12:00,2015-12-31 04:27:00,1439,1435.0,286,270.0,12.0,267.0
5819076,2015,12,31,4,B6,1503,N913JB,JFK,SJU,-9.0,...,2015-12-31 04:40:00,2015-12-31 04:32:00,2015-12-31 00:07:00,2015-12-31 04:24:00,1439,1430.0,280,272.0,7.0,264.0
5819077,2015,12,31,4,B6,333,N527JB,MCO,SJU,-6.0,...,2015-12-31 03:40:00,2015-12-31 03:30:00,2015-12-31 00:03:00,2015-12-31 03:27:00,1439,1433.0,220,210.0,3.0,207.0
5819078,2015,12,31,4,B6,839,N534JB,JFK,BQN,15.0,...,2015-12-31 04:40:00,2015-12-31 04:42:00,2015-12-31 00:28:00,2015-12-31 04:37:00,1439,14.0,280,282.0,28.0,277.0

In [23]:
flights_df.columns.tolist()

['YEAR',
 'MONTH',
 'DAY',
 'DAY_OF_WEEK',
 'AIRLINE',
 'FLIGHT_NUMBER',
 'TAIL_NUMBER',
 'ORIGIN_AIRPORT',
 'DESTINATION_AIRPORT',
 'SCHEDULED_DEPARTURE',
 'DEPARTURE_TIME',
 'DEPARTURE_DELAY',
 'TAXI_OUT',
 'WHEELS_OFF',
 'SCHEDULED_TIME',
 'ELAPSED_TIME',
 'AIR_TIME',
 'DISTANCE',
 'WHEELS_ON',
 'TAXI_IN',
 'SCHEDULED_ARRIVAL',
 'ARRIVAL_TIME',
 'ARRIVAL_DELAY',
 'DIVERTED',
 'CANCELLED',
 'CANCELLATION_REASON',
 'AIR_SYSTEM_DELAY',
 'SECURITY_DELAY',
 'AIRLINE_DELAY',
 'LATE_AIRCRAFT_DELAY',
 'WEATHER_DELAY',
 'SCHEDULED_DEPARTURE_dt',
 'DEPARTURE_TIME_dt',
 'SCHEDULED_ARRIVAL_dt',
 'ARRIVAL_TIME_dt',
 'WHEELS_OFF_dt',
 'WHEELS_ON_dt',
 'SCHEDULED_DEPARTURE_dt_min',
 'DEPARTURE_TIME_dt_min',
 'SCHEDULED_ARRIVAL_dt_min',
 'ARRIVAL_TIME_dt_min',
 'WHEELS_OFF_dt_min',
 'WHEELS_ON_dt_min']

In [24]:
## Data Cleaning / Missing Value Imputation

cancellation_map = {
    'A': 'Airline/Carrier',
    'B': 'Weather',
    'C': 'National Air System',
    'D': 'Security'
}

delays_cols = [
    "AIR_SYSTEM_DELAY",
    "SECURITY_DELAY",
    "AIRLINE_DELAY",
    "LATE_AIRCRAFT_DELAY",
    "WEATHER_DELAY"
]

flights_df['TAIL_NUMBER'] = flights_df['TAIL_NUMBER'].fillna(value='UNKNOWN')
flights_df['CANCELLATION_REASON'] = flights_df['CANCELLATION_REASON'].map(cancellation_map).fillna('Not cancelled')

for delay_col in delays_cols:
    flights_df[delay_col] = flights_df[delay_col].fillna(value=0)

In [25]:
flights_df.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,SCHEDULED_ARRIVAL_dt,ARRIVAL_TIME_dt,WHEELS_OFF_dt,WHEELS_ON_dt,SCHEDULED_DEPARTURE_dt_min,DEPARTURE_TIME_dt_min,SCHEDULED_ARRIVAL_dt_min,ARRIVAL_TIME_dt_min,WHEELS_OFF_dt_min,WHEELS_ON_dt_min
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,0005,...,2015-01-01 04:30:00,2015-01-01 04:08:00,2015-01-01 00:15:00,2015-01-01 04:04:00,5,1434.0,270,248.0,15.0,244.0
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,0010,...,2015-01-01 07:50:00,2015-01-01 07:41:00,2015-01-01 00:14:00,2015-01-01 07:37:00,10,2.0,470,461.0,14.0,457.0
2,2015,1,1,4,US,840,N171US,SFO,CLT,0020,...,2015-01-01 08:06:00,2015-01-01 08:11:00,2015-01-01 00:34:00,2015-01-01 08:00:00,20,18.0,486,491.0,34.0,480.0
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,0020,...,2015-01-01 08:05:00,2015-01-01 07:56:00,2015-01-01 00:30:00,2015-01-01 07:48:00,20,15.0,485,476.0,30.0,468.0
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,0025,...,2015-01-01 03:20:00,2015-01-01 02:59:00,2015-01-01 00:35:00,2015-01-01 02:54:00,25,24.0,200,179.0,35.0,174.0

In [28]:
### Data normalization and standardization

num_cols = [
    'DEPARTURE_DELAY', 'TAXI_OUT', 'ELAPSED_TIME', 'AIR_TIME',
    'DISTANCE', 'TAXI_IN','ARRIVAL_DELAY','AIR_SYSTEM_DELAY',
    'SECURITY_DELAY', 'AIRLINE_DELAY','LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY'
]

time_min_cols = [
    'SCHEDULED_DEPARTURE_dt_min', 'DEPARTURE_TIME_dt_min',
    'SCHEDULED_ARRIVAL_dt_min', 'ARRIVAL_TIME_dt_min',
    'WHEELS_OFF_dt_min', 'WHEELS_ON_dt_min'
]


cat_cols = [
    'CANCELLATION_REASON', 'AIR_SYSTEM_DELAY','SECURITY_DELAY','AIRLINE_DELAY','LATE_AIRCRAFT_DELAY','WEATHER_DELAY'
]


numeric_cols = num_cols + time_min_cols


preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numeric_cols),
    ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
])